version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - gosec
    - nilerr
    - misspell
  settings:
    gosec:
      excludes:
        - G204  # subprocess launched with variable — intentional for kubectl exec
    revive:
      rules:
        - name: exported
        - name: var-naming

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/be0x74a/kubectl-xctx

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
