run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - revive
    - gosec
    - nilerr
    - misspell

linters-settings:
  goimports:
    local-prefixes: github.com/be0x74a/kubectl-xctx
  gosec:
    excludes:
      - G204  # subprocess launched with variable — intentional for kubectl exec
  revive:
    rules:
      - name: exported
      - name: var-naming

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
